### ISSUE TITLE
Add new feature, new output

### ISSUE THREAD

**Issue by StysPaul** [pdxgx/pepsickle#6]
Hello,

I've installed and tested pepsickle, and everything works fine.

I would like to use pepsickle on a large fasta file. The idea is to then look at the binding of the cleaved peptides with netMHCpan (this allows the fasta to be pre-filtered and the result to be closer to biological reality). Is it possible to have an output still in text format but with different contents: 
protein identifier | cleavage start position | cleavage end position | peptide sequence | peptide length | cleavage probability
(inspired by http://tools.iedb.org/media/mhciinp/mhciinp_results_2024-09-21_1726882425.txt)

I think I could code this around pepsickle but it would be less optimised than if it were directly integrated. Is this possible?

**Comment by reidt03** [comment]
thanks for your query and your interest - sorry to say we are not developing this tool further at this time (aside from the most basic of maintenance) so any formatting requests are going to have to involve a homegrown workaround such as the one you suggest.
